# Generated by Django 3.1.1 on 2020-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat1', models.CharField(max_length=50)),
                ('feat2', models.CharField(max_length=50)),
                ('feat3', models.CharField(max_length=50)),
                ('feat4', models.CharField(max_length=50)),
                ('feat5', models.CharField(max_length=50)),
                ('feat6', models.CharField(max_length=50)),
                ('feat7', models.CharField(max_length=50)),
                ('feat8', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='sellingFeatures',
        ),
    ]
