# Generated by Django 3.1.1 on 2020-09-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_auto_20200902_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingfeatures',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='backendapp.car'),
            preserve_default=False,
        ),
    ]
